version: "3"

services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3307
    volumes:
      - "wp-db:/var/lib/mysql:rw"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
  web:
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    restart: always
    ports:
      - 8085:80
    depends_on:
      - db

volumes:
  wp-db: {}



